on:
  issue_comment:
    types: [created]
name: Document
jobs:
  document:
    name: document
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Document
        uses: jimhester/document-v2@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
