on:
  push:
    branches: master

name: Pkgdown

jobs:
  pkgdown:
    env:
      CI: true
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("remotes")' \
                  -e 'remotes::install_deps(dependencies = TRUE)' \
                  -e 'remotes::install_github("jimhester/pkgdown@github-actions-deploy")'
      - name: Install pandoc
        env:
          PANDOC_VERSION: 2.7.3
        run: |
           curl -fLo /tmp/pandoc.pkg "https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/pandoc-${PANDOC_VERSION}-macOS.pkg"
           sudo installer -pkg "/tmp/pandoc.pkg" -target /
           rm /tmp/pandoc.pkg
      - name: Install package
        run: R CMD INSTALL .
      - name: Deploy package
        run: |
          Rscript -e "pkgdown:::deploy_local(new_process = FALSE, remote_url = 'x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git')"
