name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        r: ['3.4', '3.5', '3.6']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup R
        uses: jimhester/setup-r@master
        with:
          r-version: ${{ matrix.r }}
      - name: Install package dependencies
        run: |
          Rscript -e 'install.packages(c("remotes", "rcmdcheck"))'
          Rscript -e 'remotes::install_deps(dependencies=TRUE)'
      - name: Check package
        run: Rscript -e 'rcmdcheck::rcmdcheck(args="--no-manual", error_on="error", check_dir="check")'
